# Generated by Django 5.2.9 on 2025-12-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK', 'Bank Transfer'), ('CARD', 'Card'), ('REFUND', 'Refund')], max_length=10),
        ),
    ]
